version: '3.8'

services:

  auth:
    build:
      context: ./app/auth
      dockerfile: Dockerfile
    container_name: ajigo_auth
    ports:
      - "8001:8000"
    env_file:
      - .env
    restart: unless-stopped

  usuarios:
    build:
      context: ./app/usuarios
      dockerfile: Dockerfile
    container_name: ajigo_usuarios
    ports:
      - "8002:8000"
    env_file:
      - .env
    restart: unless-stopped

  catalogo:
    build:
      context: ./app/catalogo
      dockerfile: Dockerfile
    container_name: ajigo_catalogo
    ports:
      - "8003:8000"
    env_file:
      - .env
    restart: unless-stopped

  pedidos:
    build:
      context: ./app/pedidos
      dockerfile: Dockerfile
    container_name: ajigo_pedidos
    ports:
      - "8004:8000"
    env_file:
      - .env
    restart: unless-stopped
